### ISSUE TITLE
File /lib/bulldog-linux-native-beagleboneblack-hardfp.so was not found in classpath

### ISSUE THREAD

**Issue by pmacik** [px3/bulldog#44] opened 2015-07-16 08:58 UTC
From email by:   dmytro.minochkin@gmail.com

Test app builds fine, but when i execute it on the BBB an error occurs:
"File /lib/bulldog-linux-native-beagleboneblack-hardfp.so was not found in classpath".
checking both the uber-jar and jars from maven i've found they have the required file, but it is named either "bulldog-linux-native-beagleboneblack-0.1.2.so" or "bulldog-linux-native-beagleboneblack.so".
Simply renaming it inside the jar worked, but i don't think it's a valid long time fix.

**Comment by sbunciak** [comment] 2015-08-08 20:58
Duplicate of #40

**Closed by sbunciak** 2015-08-08 20:58 UTC
Labels: bug
